
lines (21 sloc)  523 Bytes

name: 'basetables'
version: '0.5'

profile: 'sagar.midaxo'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false

models:
  materialized: view
  post-hook:
      - "grant select on {{this}} to SYSADMIN"
  function:
    enabled: false
