name: 'basetables'
version: '0.5'

profile: 'sagar.midaxo'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false

models:
  materialized: view
  post-hook:
      - "grant select on {{this}} to SYSADMIN"
  function:
    enabled: false

archive:
    - source_schema: DEV                     # schema to look for tables in (declared below)
      target_schema: DEV                     # where to archive the data to
      tables:                                # list of tables to archive
        - source_table: DEAL                # table to archive (production_data.users)
          target_table: DEAL_ARCHIVE       # table to insert archived data into (dbt_archive.users_archived)
          updated_at: 'changedate::timestamp_ntz'            # used to determine when data has changed
          unique_key: deal_id                     # used to generate archival query
